name: Update sslime336.github.io
on:
  push:
    branches:
      - hugo

jobs:
  deploy2master:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code on branch hugo
        uses: actions/checkout@v3
        with:
          ref: hugo
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Build
        run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          external_repository: sslime336/sslime336.github.io # Page 仓库
          publish_branch: master # Page 仓库的分支
          publish_dir: ./public # 静态网页路径
          commit_message: ${{ github.event.head_commit.message }}
